language: python

python:
  - 2.7

notifications:
  email: false

sudo: required

dist: trusty

cache:
  - pip
  - apt

addons:
   apt:
     packages:
       - nginx
       - supervisor
       - python-dev
       - liblapack-dev
       - libmemcached-dev
       - memcached
       - g++
       - libxslt1-dev
       - libhdf5-serial-dev
       - libjpeg-dev
       - mysql-server-5.6
       - mysql-client-core-5.6
       - mysql-client-5.6

services:
  - mysql
  - memcached
  - rabbitmq
  - supervisor
  - nginx
  - redis

before_install:
  #- echo "mysql-server-5.6 mysql-server/root_password password neur0data" | sudo debconf-set-selections
  #- echo "mysql-server-5.6 mysql-server/root_password_again password neur0data" | sudo debconf-set-selections
  - sudo mkdir /var/log/neurodata
  - sudo touch /var/log/neurodata/nd.log
  - sudo chown -R www-data:www-data /var/log/neurodata
  - sudo chmod -R 777 /var/log/neurodata/

install: 
  #- sudo apt-get -y install mysql-client-core-5.6 libhdf5-serial-dev mysql-client-5.6  
  #- sudo apt-get -y install libxslt1-dev libmemcached-dev libhdf5-serial-dev g++ libjpeg-dev python-dev mysql-server-5.6 libmysqlclient-dev supervisor uwsgi uwsgi-plugin-python liblapack-dev
  - sudo apt-get -y install uwsgi uwsgi-plugin-python
  - pip install cython numpy
  - pip install -r ./setup/requirements.txt
    # compiling the ctypes lib
  - make -f /home/travis/build/neurodata/ndstore/ndlib/c_version/makefile_LINUX -C ./ndlib/c_version/
    # creating the mysql user
  #- sudo service mysql restart
  - mysql -u root -i -e "create user 'neurodata'@'localhost' identified by 'neur0data';" && mysql -u root -i -e "grant all privileges on *.* to 'neurodata'@'localhost' with grant option;" && mysql -u neurodata -pneur0data -i -e "CREATE DATABASE neurodjango;"
    # settings and secret_settings
  - cp ./django/ND/settings.py.example ./django/ND/settings.py
  - ln -s /home/travis/build/neurodata/ndstore/setup/docker_config/django/docker_settings_secret.py /home/travis/build/neurodata/ndstore/django/ND/settings_secret.py
    # django migrate
  - python ./django/manage.py migrate
  - echo "from django.contrib.auth.models import User; User.objects.create_superuser('neurodata', 'abc@xyz.com', 'neur0data')" | python ./django/manage.py shell
  - python ./django/manage.py collectstatic --noinput
    # move the nginx config files and start service
  #- sudo rm /etc/nginx/sites-enabled/default
  - sudo ln -s ./setup/docker_config/nginx/neurodata.conf /etc/nginx/sites-enabled/neurodata.conf
    # move uwsgi config files and start service
  - sudo ln -s ./setup/docker_config/uwsgi/neurodata.ini /etc/uwsgi/apps-available/
  - sudo ln -s ./setup/docker_config/uwsgi/neurodata.ini /etc/uwsgi/apps-enabled/
    # move celery config files and start service
  - sudo ln -s ./setup/docker_config/celery/propagate.conf /etc/supervisor/conf.d/propagate.conf
  - sudo ln -s ./setup/docker_config/celery/ingest.conf /etc/supervisor/conf.d/ingest.conf
    # restarting all the services
  - sudo service nginx restart
  - sudo service uwsgi restart
  - sudo service supervisor restart
  - sudo service rabbitmq-server restart
  - sudo service memcached restart

services:
  - mysql
  - memcached
  - rabbitmq
  - supervisor
  - nginx
  - redis

script:
  - wget localhost
  - wget localhost/nd/accounts/login
  - cd ./test/
  - py.test
